/**
 * TypeORM Database Entity representing PAYMENT data model.
 * Defines table schema, column properties, and relationship mappings.
 */
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn } from 'typeorm';

/**
 * Payment Entity — maps to the 'payments' table in the database.
 * This entity records every transaction where a student pays their tuition fee.
 */
@Entity('payments')
export class Payment {
  /** Auto-incrementing primary key */
  @PrimaryGeneratedColumn()
  id: number;

  /** The ID of the student making the payment (references the students table ID) */
  @Column()
  studentId: number;

  /** The amount of money paid in this transaction */
  @Column({ type: 'float' })
  amountPaid: number;

  /** The date/time when the transaction took place */
  @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
  paymentDate: Date;

  /** 
   * A unique receipt number generated by the system for verification and reporting.
   * e.g., "REC-2026-XXXXXX"
   */
  /**
   * Associated property field: receiptNumber.
   */
  @Column({ unique: true })
  receiptNumber: string;

  /** The academic year this payment is credited to (e.g. 2026) */
  @Column({ type: 'int' })
  academicYear: number;

  /** The semester this payment is credited to (e.g. 1 or 2) */
  @Column({ type: 'int' })
  semester: number;

  /** Automatically set to the date/time this payment record was created in the database */
  @CreateDateColumn()
  createdAt: Date;

  /** Automatically updated whenever the payment record changes */
  @UpdateDateColumn()
  updatedAt: Date;
}
